# Imports

In [1]:
import torch
torch.__version__

'2.5.1'

In [2]:
if torch.cuda.is_available():
    print("CUDA is available, and using", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available, using CPU only.")

CUDA is available, and using NVIDIA GeForce GTX 1660 Ti


# Creating Tensor

using empty

In [3]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

using zeros

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

using ones

In [6]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

using full

In [7]:
torch.full((2, 3), 9) # numpy full_like

tensor([[9, 9, 9],
        [9, 9, 9]])

using random

In [8]:
torch.rand(2, 3) # every run, different random numbers

tensor([[0.0768, 0.8135, 0.8817],
        [0.1261, 0.2251, 0.7718]])

In [9]:
torch.manual_seed(100) # for reproducibility
torch.rand(2, 3) # every run, same random numbers

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

custom tensor

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

using range

In [11]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(start=0, end=1, steps=5) # same like numpy

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

using matrix

In [13]:
torch.eye(3) # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Tensor Shapes

In [14]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [15]:
torch.empty_like(x) # using x shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.rand_like(x, dtype=torch.float32) # to avoid error add dtype as float, since its returns float

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Type

In [18]:
x.dtype

torch.int64

assign dtype

In [19]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

changing dtype

In [21]:
l = torch.tensor([1, 2, 3])
print(l.dtype)
l.to(torch.float32)

torch.int64


tensor([1., 2., 3.])