# Imports

In [1]:
import torch
torch.__version__

'2.5.1'

In [2]:
if torch.cuda.is_available():
    print("CUDA is available, and using", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available, using CPU only.")

CUDA is available, and using NVIDIA GeForce GTX 1660 Ti


# Creating Tensor

using empty

In [3]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

using zeros

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

using ones

In [6]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

using full

In [7]:
torch.full((2, 3), 9) # numpy full_like

tensor([[9, 9, 9],
        [9, 9, 9]])

using random

In [8]:
torch.rand(2, 3) # every run, different random numbers

tensor([[0.5480, 0.6349, 0.8079],
        [0.3529, 0.7291, 0.1094]])

In [9]:
torch.manual_seed(100) # for reproducibility
torch.rand(2, 3) # every run, same random numbers

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

custom tensor

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

using range

In [11]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(start=0, end=1, steps=5) # same like numpy

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

using matrix

In [13]:
torch.eye(3) # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Tensor Shapes

In [14]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [15]:
torch.empty_like(x) # using x shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.rand_like(x, dtype=torch.float32) # to avoid error add dtype as float, since its returns float

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Type

In [18]:
x.dtype

torch.int64

assign dtype

In [19]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

changing dtype

In [21]:
l = torch.tensor([1, 2, 3])
print(l.dtype)
l.to(torch.float32)

torch.int64


tensor([1., 2., 3.])

# Mathematical Operations

In [22]:
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

scalar operations

In [23]:
# addition
x + 2

# subtraction
x - 9.5

# multiplication
x * 3

# division
x / 2

# int division
x // 0.5

# mod
x % 0.7

# power
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

element-wise operations

In [24]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.9969, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]),
 tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]))

In [25]:
# add
a + b

# subtract
a - b

# multiply
a * b

# divide
a / b

# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

self-wise operations

In [26]:
c = torch.tensor([1.2, -3.4, 5.6, -7.8])

In [27]:
torch.abs(c)

tensor([1.2000, 3.4000, 5.6000, 7.8000])

In [28]:
torch.neg(c)

tensor([-1.2000,  3.4000, -5.6000,  7.8000])

In [29]:
torch.round(c)

tensor([ 1., -3.,  6., -8.])

In [30]:
torch.ceil(c)

tensor([ 2., -3.,  6., -7.])

In [31]:
torch.floor(c)

tensor([ 1., -4.,  5., -8.])

In [32]:
torch.clamp(c, min=-1.0, max=5.0)

tensor([ 1.2000, -1.0000,  5.0000, -1.0000])

reduction operations

In [33]:
d = torch.randint(size=(4,5), low=0, high=10, dtype=torch.float32)
d

tensor([[8., 0., 7., 0., 0.],
        [9., 5., 7., 3., 9.],
        [4., 0., 5., 7., 5.],
        [9., 9., 7., 5., 9.]])

In [34]:
# sum
torch.sum(d)
# sum along columns
torch.sum(d, dim=0)
# sum along rows
torch.sum(d, dim=1)

tensor([15., 33., 21., 39.])

In [35]:
# mean
torch.mean(d)
# mean along columns
torch.mean(d, dim=0)
# mean along rows
torch.mean(d, dim=1)

tensor([3.0000, 6.6000, 4.2000, 7.8000])

In [36]:
# median
torch.median(d)
# median along columns
torch.median(d, dim=0)
# median along rows
torch.median(d, dim=1)

torch.return_types.median(
values=tensor([0., 7., 5., 9.]),
indices=tensor([4, 2, 2, 0]))

In [37]:
# min & max
torch.min(d), torch.max(d)

(tensor(0.), tensor(9.))

In [38]:
# argmin & argmax
torch.argmin(d), torch.argmax(d)

(tensor(1), tensor(5))

In [39]:
# prod
torch.prod(d)

tensor(0.)

In [40]:
# std & var
torch.std(d), torch.var(d)

(tensor(3.2991), tensor(10.8842))

matrix operations

In [41]:
m = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
n = torch.randint(size=(3,4), low=0, high=10, dtype=torch.float32)

m, n

(tensor([[8., 9., 7.],
         [9., 2., 6.]]),
 tensor([[7., 7., 8., 3.],
         [6., 1., 5., 5.],
         [0., 4., 3., 8.]]))

In [42]:
# matrix mul
torch.matmul(m, n)

tensor([[110.,  93., 130., 125.],
        [ 75.,  89., 100.,  85.]])

In [43]:
# matrix dot-product
v1 = torch.tensor([1, 2])
v2 = torch.tensor([7, 9])

torch.dot(v1, v2)

tensor(25)

In [44]:
# transpose
torch.transpose(m, dim0=0, dim1=1) # dim0 swaps with dim1

tensor([[8., 9.],
        [9., 2.],
        [7., 6.]])

In [45]:
# determinant
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

torch.det(p)

tensor(31.)

In [46]:
# inverse
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

torch.inverse(p)

tensor([[0.0000, 0.2500],
        [0.1667, 0.0000]])

comparision operations

In [47]:
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)
q = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

p, q

(tensor([[8., 4.],
         [7., 2.]]),
 tensor([[3., 8.],
         [5., 6.]]))

In [48]:
# greater than
p > q

# less than
p < q

# equal to
p == q

# not equal to
p != q

# greater than eual to
p >= q

# less than eual to
p <= q

tensor([[False,  True],
        [False,  True]])

special functions

In [49]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 9., 5.],
        [0., 4., 2.]])

In [50]:
# log & exp
torch.log(k), torch.exp(k)

(tensor([[0.6931, 2.1972, 1.6094],
         [  -inf, 1.3863, 0.6931]]),
 tensor([[7.3891e+00, 8.1031e+03, 1.4841e+02],
         [1.0000e+00, 5.4598e+01, 7.3891e+00]]))

In [51]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 3.0000, 2.2361],
        [0.0000, 2.0000, 1.4142]])

In [52]:
# sigmoid, softmax, relu
torch.sigmoid(k), torch.softmax(k, dim=1), torch.relu(k)

(tensor([[0.8808, 0.9999, 0.9933],
         [0.5000, 0.9820, 0.8808]]),
 tensor([[8.9468e-04, 9.8114e-01, 1.7970e-02],
         [1.5876e-02, 8.6681e-01, 1.1731e-01]]),
 tensor([[2., 9., 5.],
         [0., 4., 2.]]))

inplace operations

In [53]:
u = torch.randint(size=(2,3), low=0, high=10)
v = torch.randint(size=(2,3), low=0, high=10)
u, v

(tensor([[7, 1, 1],
         [5, 4, 4]]),
 tensor([[1, 1, 2],
         [4, 7, 2]]))

In [54]:
u.add_(v), u  # inplace addition, sometimes to save memory, we are saving results in the prime tensor itself

(tensor([[ 8,  2,  3],
         [ 9, 11,  6]]),
 tensor([[ 8,  2,  3],
         [ 9, 11,  6]]))

# w