# Imports

In [1]:
import torch
torch.__version__

'2.5.1'

In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("CUDA is available, and using", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("CUDA is not available, using CPU only.")

CUDA is available, and using NVIDIA GeForce GTX 1660 Ti


# Creating Tensor

using empty

In [3]:
a = torch.empty(2, 3)
a

tensor([[3.6913e+19, 1.5695e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
type(a)

torch.Tensor

using zeros

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

using ones

In [6]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

using full

In [7]:
torch.full((2, 3), 9) # numpy full_like

tensor([[9, 9, 9],
        [9, 9, 9]])

using random

In [8]:
torch.rand(2, 3) # every run, different random numbers

tensor([[0.5553, 0.4080, 0.7546],
        [0.4055, 0.7851, 0.5055]])

In [9]:
torch.manual_seed(100) # for reproducibility
torch.rand(2, 3) # every run, same random numbers

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

custom tensor

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

using range

In [11]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(start=0, end=1, steps=5) # same like numpy

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

using matrix

In [13]:
torch.eye(3) # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Tensor Shapes

In [14]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [15]:
torch.empty_like(x) # using x shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.rand_like(x, dtype=torch.float32) # to avoid error add dtype as float, since its returns float

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Reshaping

In [18]:
a = torch.randint(size=(4, 4), low=0, high=10)
a

tensor([[8, 8, 4, 4],
        [1, 0, 4, 3],
        [8, 7, 4, 6],
        [0, 1, 9, 9]])

reshape

In [19]:
a.reshape(2, 2, 2, 2)

tensor([[[[8, 8],
          [4, 4]],

         [[1, 0],
          [4, 3]]],


        [[[8, 7],
          [4, 6]],

         [[0, 1],
          [9, 9]]]])

flatten

In [20]:
a.flatten()

tensor([8, 8, 4, 4, 1, 0, 4, 3, 8, 7, 4, 6, 0, 1, 9, 9])

permute

In [21]:
b = torch.randn(2, 3, 4)
print('b is', b, 'and shape is', b.shape)

b.permute(2, 0, 1).shape # changes the dimension order by index


b is tensor([[[ 0.7139, -0.4200,  0.6375,  0.5812],
         [-1.7599,  1.0230, -0.1107, -0.3899],
         [-0.3668, -0.4251, -1.2455,  1.1245]],

        [[ 1.3302,  0.0544,  0.3736, -1.4024],
         [ 1.0412, -0.8043, -0.6244, -0.5882],
         [-0.7553, -0.9577, -2.1387, -1.2822]]]) and shape is torch.Size([2, 3, 4])


torch.Size([4, 2, 3])

unsqueeze & squeeze

In [22]:
c = torch.rand(256, 256, 3) # height, width, color channels
c.unsqueeze(0).shape # add batch dimension at index 0

torch.Size([1, 256, 256, 3])

In [23]:
d = torch.rand(1, 5)
print(d, d.shape)
d.squeeze_(0)
d, d.shape

tensor([[0.8252, 0.3159, 0.4104, 0.3669, 0.3880]]) torch.Size([1, 5])


(tensor([0.8252, 0.3159, 0.4104, 0.3669, 0.3880]), torch.Size([5]))

# Tensor Data Type

In [24]:
x.dtype

torch.int64

assign dtype

In [25]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

changing dtype

In [27]:
l = torch.tensor([1, 2, 3])
print(l.dtype)
l.to(torch.float32)

torch.int64


tensor([1., 2., 3.])

# Mathematical Operations

In [28]:
x = torch.rand(2, 2)
x

tensor([[0.4139, 0.8138],
        [0.8343, 0.9886]])

scalar operations

In [29]:
# addition
x + 2

# subtraction
x - 9.5

# multiplication
x * 3

# division
x / 2

# int division
x // 0.5

# mod
x % 0.7

# power
x ** 2

tensor([[0.1713, 0.6622],
        [0.6961, 0.9773]])

element-wise operations

In [30]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.1998, 0.8756, 0.3590],
         [0.0577, 0.3814, 0.2971]]),
 tensor([[0.4993, 0.8849, 0.8621],
         [0.5653, 0.4300, 0.7539]]))

In [31]:
# add
a + b

# subtract
a - b

# multiply
a * b

# divide
a / b

# power
a ** b

tensor([[0.4475, 0.8891, 0.4135],
        [0.1994, 0.6607, 0.4005]])

self-wise operations

In [32]:
c = torch.tensor([1.2, -3.4, 5.6, -7.8])

In [33]:
torch.abs(c)

tensor([1.2000, 3.4000, 5.6000, 7.8000])

In [34]:
torch.neg(c)

tensor([-1.2000,  3.4000, -5.6000,  7.8000])

In [35]:
torch.round(c)

tensor([ 1., -3.,  6., -8.])

In [36]:
torch.ceil(c)

tensor([ 2., -3.,  6., -7.])

In [37]:
torch.floor(c)

tensor([ 1., -4.,  5., -8.])

In [38]:
torch.clamp(c, min=-1.0, max=5.0)

tensor([ 1.2000, -1.0000,  5.0000, -1.0000])

reduction operations

In [39]:
d = torch.randint(size=(4,5), low=0, high=10, dtype=torch.float32)
d

tensor([[0., 9., 0., 1., 5.],
        [8., 1., 0., 7., 8.],
        [3., 9., 0., 7., 5.],
        [3., 6., 7., 8., 4.]])

In [40]:
# sum
torch.sum(d)
# sum along columns
torch.sum(d, dim=0)
# sum along rows
torch.sum(d, dim=1)

tensor([15., 24., 24., 28.])

In [41]:
# mean
torch.mean(d)
# mean along columns
torch.mean(d, dim=0)
# mean along rows
torch.mean(d, dim=1)

tensor([3.0000, 4.8000, 4.8000, 5.6000])

In [42]:
# median
torch.median(d)
# median along columns
torch.median(d, dim=0)
# median along rows
torch.median(d, dim=1)

torch.return_types.median(
values=tensor([1., 7., 5., 6.]),
indices=tensor([3, 3, 4, 1]))

In [43]:
# min & max
torch.min(d), torch.max(d)

(tensor(0.), tensor(9.))

In [44]:
# argmin & argmax
torch.argmin(d), torch.argmax(d)

(tensor(0), tensor(1))

In [45]:
# prod
torch.prod(d)

tensor(0.)

In [46]:
# std & var
torch.std(d), torch.var(d)

(tensor(3.3162), tensor(10.9974))

matrix operations

In [47]:
m = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
n = torch.randint(size=(3,4), low=0, high=10, dtype=torch.float32)

m, n

(tensor([[6., 2., 6.],
         [5., 3., 2.]]),
 tensor([[7., 7., 5., 9.],
         [5., 9., 2., 2.],
         [8., 3., 7., 4.]]))

In [48]:
# matrix mul
torch.matmul(m, n)

tensor([[100.,  78.,  76.,  82.],
        [ 66.,  68.,  45.,  59.]])

In [49]:
# matrix dot-product
v1 = torch.tensor([1, 2])
v2 = torch.tensor([7, 9])

torch.dot(v1, v2)

tensor(25)

In [50]:
# transpose
torch.transpose(m, dim0=0, dim1=1) # dim0 swaps with dim1

tensor([[6., 5.],
        [2., 3.],
        [6., 2.]])

In [51]:
# determinant
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

torch.det(p)

tensor(6.)

In [52]:
# inverse
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

torch.inverse(p)

tensor([[ 0.2500, -0.0556],
        [-0.2500,  0.1667]])

comparision operations

In [53]:
p = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)
q = torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32)

p, q

(tensor([[3., 5.],
         [2., 5.]]),
 tensor([[6., 9.],
         [8., 6.]]))

In [54]:
# greater than
p > q

# less than
p < q

# equal to
p == q

# not equal to
p != q

# greater than eual to
p >= q

# less than eual to
p <= q

tensor([[True, True],
        [True, True]])

special functions

In [55]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 1., 9.],
        [0., 6., 3.]])

In [56]:
# log & exp
torch.log(k), torch.exp(k)

(tensor([[1.3863, 0.0000, 2.1972],
         [  -inf, 1.7918, 1.0986]]),
 tensor([[5.4598e+01, 2.7183e+00, 8.1031e+03],
         [1.0000e+00, 4.0343e+02, 2.0086e+01]]))

In [57]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 1.0000, 3.0000],
        [0.0000, 2.4495, 1.7321]])

In [58]:
# sigmoid, softmax, relu
torch.sigmoid(k), torch.softmax(k, dim=1), torch.relu(k)

(tensor([[0.9820, 0.7311, 0.9999],
         [0.5000, 0.9975, 0.9526]]),
 tensor([[6.6906e-03, 3.3311e-04, 9.9298e-01],
         [2.3556e-03, 9.5033e-01, 4.7314e-02]]),
 tensor([[4., 1., 9.],
         [0., 6., 3.]]))

inplace operations

In [59]:
u = torch.randint(size=(2,3), low=0, high=10)
v = torch.randint(size=(2,3), low=0, high=10)
u, v

(tensor([[8, 3, 0],
         [3, 2, 5]]),
 tensor([[0, 0, 3],
         [1, 1, 4]]))

In [60]:
u.add_(v), u  # inplace addition, sometimes to save memory, we are saving results in the prime tensor itself

(tensor([[8, 3, 3],
         [4, 3, 9]]),
 tensor([[8, 3, 3],
         [4, 3, 9]]))

# Tensor on GPU