# Imports

In [1]:
import torch
torch.__version__

'2.5.1'

In [2]:
if torch.cuda.is_available():
    print("CUDA is available, and using", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available, using CPU only.")

CUDA is available, and using NVIDIA GeForce GTX 1660 Ti


# Creating Tensor

using empty

In [3]:
a = torch.empty(2, 3)
a

tensor([[5.9442e+28, 1.6423e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
type(a)

torch.Tensor

using zeros

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

using ones

In [6]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

using full

In [7]:
torch.full((2, 3), 9) # numpy full_like

tensor([[9, 9, 9],
        [9, 9, 9]])

using random

In [8]:
torch.rand(2, 3) # every run, different random numbers

tensor([[0.7460, 0.3231, 0.9070],
        [0.8711, 0.0365, 0.4331]])

In [9]:
torch.manual_seed(100) # for reproducibility
torch.rand(2, 3) # every run, same random numbers

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

custom tensor

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

using range

In [11]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(start=0, end=1, steps=5) # same like numpy

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

using matrix

In [13]:
torch.eye(3) # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])